/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

*/

const findTheDifference = (s, t) => {
  const freq = {};

  for (const char of s) {
    freq[char] = (freq[char] || 0) + 1
  }

  for (const char of t) {
    if (!freq[char]) {
      return char;
    }
    freq[char]--
  }
};

console.log(findTheDifference("abcd", "abcde"))